### ISSUE TITLE
Creating tokens over a dictionary

### ISSUE THREAD

**Issue by benfig1127** [benfig1127/Summer-Research-2020#8]
@mikeizbicki Hey mike, I was able to get the code to create the correct dictionaries over a folder full of text files as we had discussed. I am currently having trouble iterating over the dictionary to create the tokens for the values of the dictionary. Here is the code for obtaining the dictionary and iterating over it to create the tokens.
```
def data_parser():
	language_lines={}
	all_languages=[]
	i=0
	j=0
	for filename in glob.glob(os.path.join(args.data,'*')):	
		i+=1				
		name = os.path.basename(filename)
		if args.print_filenames:
			print('filename',i,'->',name)
		language = os.path.splitext(os.path.basename(filename))[0]			
		all_languages.append(language)
		lines = open(filename, encoding='utf-8').read().strip().split('\n')
		lines = [format_line(line) for line in lines]
		language_lines[language]=lines
	language_lines_vals=language_lines.values()	
	if args.print_keys:
		for language in language_lines:
			j+=1			
			print('key',j,'->',language) 
	if args.print_vals:
		print(language_lines_vals)
	if args.print_all_items:
		print(language_lines.items())
		
	for lang in language_lines:
		tokens=tokenizer.tokenize(lang)
	if args.print_tokens:
		print('tokens ->',tokens)
```
As its stands it seems to only tokenize the names of the files not the actual file itself. Here is the output as its stands. 
```
tokens -> ['test', '_', 'un', '##v', '##1', '.', '0', '.', 'en', '-', 'es', '.', 'es']
```

 I tried accessing only the values by changing the for loop to the following.

```
for lang in language_lines.values():
		tokens=tokenizer.tokenize(lang)
	if args.print_tokens:
		print('tokens ->',tokens)
```

However this returns the following error:
```
Traceback (most recent call last):
  File "UN_encoder.py", line 133, in <module>
    data_parser()
  File "UN_encoder.py", line 129, in data_parser
    tokens=tokenizer.tokenize(lang)
  File "/home/ben/.local/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 768, in tokenize
    text = lowercase_text(text)
  File "/home/ben/.local/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 765, in lowercase_text
    return re.sub(pattern, lambda m: m.groups()[0] or m.groups()[1].lower(), t)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```
Can you provide me with some help of how to iterate over the dictionary values?
Thanks

**Comment by mikeizbicki** [comment]
This looks a lot more complicated than you need, and in particular the code for this part isn't very related to the code from the `names.py` file.  There's no need to loop over a directory or use the glob function.

The code should follow the pattern of
```
with open(args.filename,'r') as f_in:
    with open(args.filename+'.bert','w') as f_out:
        for line in f_in:
            line_tensor = encode_line(line)
            embedding = model(line_tensor)
            f_out.write(embedding)
```

The body of the for loop will be a bit different, and you'll need to add the argparse stuff at the top, but otherwise that's it.

**Comment by benfig1127** [comment]
I see, so there is no need to create a dictionary of all the languages, instead I can just write a new file for every text file containing the encodings?

**Comment by benfig1127** [comment]
After examining your code more, I am actually more confused. It seems that your code calls a function ``` encode_line()
```
Is this another function that actually generates the 1-hot encodings of the tensor, similar to the string to tensor function used for part 3 of the final project? If this is the case, will the original function that I wrote work for this encoding (with correct parameters and such) or do I need to re-write that as well. For reference here is the string to tensor function I originally wrote. 
```
def str_to_tensor(ss,input_length=None):
    '''
    Converts a list of strings into a tensor of shape <max_length, len(ss), len(vocabulary)>.
    This is used to convert text into a form suitable for input into a RNN/CNN.
    '''
    max_length = max([len(s) for s in ss]) + 2
    if input_length:
        max_length = input_length
    tensor = torch.zeros(max_length, len(ss), len(vocabulary)).to(device)
    for j,s in enumerate(ss):
        s = BOL + s + EOL
        for i, letter in enumerate(s):
            if i<max_length:
                vocabulary_i = vocabulary.find(letter)
                if vocabulary_i==-1:
                    vocabulary_i = vocabulary.find(OOV)
                tensor[i,j,vocabulary_i] = 1
    return tensor
```
Finally, you pass ```line_tensor``` into the ```model``` function, Im assuming your calling the same Bert model that we have already created 
```class BertFineTuning(torch.nn.Module):
    def __init__(self):
        super().__init__()
        num_classes=100
        self.fc_class = torch.nn.Linear(768,num_classes)

    def forward(self,x):
        last_layer,embedding = bert(x) 
        embedding = torch.mean(last_layer,dim=1)
        out = self.fc_class(embedding)
        return out
```

Sorry, I am still lost in terms of how these functions flow together and how I am meant to change them correctly. I originally had planned on creating a function that generates the tokens similar to the transformers_tutorial.py file and then passing this into our encoder function that generates the 1 hot encodings and then passing this to the Bert model to generate the embeddings.

**Comment by mikeizbicki** [comment]
> @mikeizbicki After examining your code more, I am actually more confused. It seems that your code calls a function ` encode_line()`

This is the same as `str_to_tensor`, I just called it something else in the pseudocode.

> Finally, you pass `line_tensor` into the `model` function, Im assuming your calling the same Bert model that we have already created

That's correct.

> Sorry, I am still lost in terms of how these functions flow together and how I am meant to change them correctly. I originally had planned on creating a function that generates the tokens similar to the transformers_tutorial.py file and then passing this into our encoder function that generates the 1 hot encodings and then passing this to the Bert model to generate the embeddings.

The inside of the for loop should look like the code from the `transformers_tutorial.py` file, you are correct.

**Comment by benfig1127** [comment]
Okay awesome, thanks! I'll work on getting this all together and show you and update tommorow afternoon durring naptime. Can we tentatively plan for 130pm?

**Comment by benfig1127** [comment]
Hey mike im working in some material right now and don't have anything to sho you yet, so I don't think a meeting in 30 minutes is helpful.
